# ~/~ begin <<docs/setup-deploy/mkdocs.md#mkdocs.yml>>[init]
site_name: Gong system and apps for Vipassane centers
site_url: https://s66erge.github.io/entan-mkdocs
repo_url: https://github.com/s66erge/entan-mkdocs

plugins:
  - search
#  - entangled
  - mermaid2:
      arguments:
         securityLevel: 'loose' 

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      linenums: true 
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          #format: !!python/name:mermaid2.fence_mermaid

theme:
  #name: readthedocs
  name: material
  features:
    - navigation.instant
    #- navigation.top
    - navigation.tab
    - navigation.path
    - content.code.copy
    - content.code.annotate # [1]
  palette: 
    #Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo 
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      code_theme: github

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      code_theme: material-dark

extra_css:
#  - stylesheets/solarized-dark.css
  - stylesheets/native.css
#  - stylesheets/one-dark.css

#extra_javascript:
#    - https://unpkg.com/mermaid/dist/mermaid.min.js

watch:
  - docs

#Bash
#pygmentize -L styles
#To generate a CSS file for your Markdown project (for example, using monokai), use:

#Bash example
#pygmentize -S monokai -f html -a .highlight > monokai.css

# ~/~ end
