# ~/~ begin <<docs/setup-deploy/mkdocs.md#mkdocs.yml>>[init]
site_name: My Docs
site_url: https://s66erge.github.io/entan-mkdocs
repo_url: https://github.com/s66erge/entan-mkdocs

plugins:
  - search
  - entangled
  - mermaid2:
      arguments:
         securityLevel: 'loose' 

#extra_javascript:
#    - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#         format: !!python/name:mermaid2.fence_mermaid
  
theme:
  name: readthedocs
  name: material
  features:
    - content.code.copy
  palette: 
    # Palette toggle for light mode
    #- scheme: default
    #  toggle:
    #    icon: material/brightness-7 
    #    name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  watch:
  - docs
# ~/~ end
