# ~/~ begin <<docs/setup-prod/local-staging.md#.devcontainer/docker-compose.staging.yml>>[init]

services:
  # 1. Your Application Staging Container
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev # Or point to your standard dev Dockerfile
      target: production
    hostname: ubuntu-bosgame
    env_file:
      - .env.staging  # including same CONTAINER_NAME
    volumes:
      - appli_data:/app/data
    ports:
      - "8000:8000" # Exposes your app's port to the host machine
    depends_on:
      db:
        condition: service_healthy
    command: ["./.venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  # 2. PostgreSQL 18 Container
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "5432:5432" # Exposes to your host machine so you can use external GUI tools like DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  appli_data:    # Persists application data
  postgres_data: # Persists your database tables even if the container restarts

# ~/~ end
